Citizen.CreateThread(function()
    TriggerEvent("chatMessage", "Tips", {0, 163, 36}, "Pon aqui tu tip/anuncio! Put there your tip or ad!")
    Citizen.Wait(100000)   
    TriggerEvent("chatMessage", "Tips", {20, 163, 36}, "Pon aqui tu tip/anuncio! Put there your tip or ad!")
    Citizen.Wait(100000)   
    TriggerEvent("chatMessage", "Tips", {40, 163, 36}, "Pon aqui tu tip/anuncio! Put there your tip or ad!")
    Citizen.Wait(100000)   
    TriggerEvent("chatMessage", "Tips", {60, 163, 36}, "Pon aqui tu tip/anuncio! Put there your tip or ad!")
    Citizen.Wait(100000)   
    TriggerEvent("chatMessage", "Tips", {80, 163, 36}, "Pon aqui tu tip/anuncio! Put there your tip or ad!")
    Citizen.Wait(100000)   
    TriggerEvent("chatMessage", "Tips", {100, 163, 36}, "Pon aqui tu tip/anuncio! Put there your tip or ad!")
    Citizen.Wait(100000)
end)
